MINIMUM_TOTAL_CONTEXT_LINES = 10
PER_FINAL_TOKEN_SAMPLE_MINIMUM = 3

GENERAL_MINIMUM_INSTRUCTION_SAMPLES: int = 3
STATE_MACHINE_MINIMUM_INSTRUCTION_SAMPLES: int = 10

MIN_SAMPLES_PER_GUARDRAIL: int = 3
